-- ======================================
-- Adventure Books Schema (PostgreSQL)
-- ======================================

-- --------------------
-- To enable case-insensitive text
-- --------------------
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


-- --------------------
-- Books
-- --------------------
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    difficulty VARCHAR(20) NOT NULL, -- Easy, Medium and Hard
    condition VARCHAR(20) NOT NULL,
    CONSTRAINT uniq_books_title_author UNIQUE (title, author)
);

-- --------------------
-- Book Categories
-- --------------------
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uniq_categories_name UNIQUE (name)
);

-- --------------------
-- books <-> categories association (many-to-many)
-- --------------------
CREATE TABLE IF NOT EXISTS book_categories (
    book_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, category_id),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

-- --------------------
-- Book Sections
-- --------------------
CREATE TABLE IF NOT EXISTS sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    section_number INT NOT NULL,
    type VARCHAR(10) NOT NULL,   -- BEGIN | NODE | END
    text TEXT NOT NULL,          -- unlimited length
    CONSTRAINT uniq_sections_book_section UNIQUE (book_id, section_number)
);

-- --------------------
-- Section Options
-- --------------------
CREATE TABLE IF NOT EXISTS options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    goto_section_number INT NOT NULL,
    CONSTRAINT uniq_options_section_description UNIQUE (section_id, description)
);

-- --------------------
-- Option Consequence
-- --------------------
CREATE TABLE IF NOT EXISTS consequences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_id BIGINT NOT NULL REFERENCES options(id) ON DELETE CASCADE,
    type VARCHAR(20) NOT NULL,   -- GAIN_HEALTH | LOSE_HEALTH
    value INT NOT NULL,
    text TEXT
);

-- --------------------
-- Games
-- --------------------
CREATE TABLE IF NOT EXISTS games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    section_id BIGINT NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    previous_section_id BIGINT REFERENCES sections(id) ON DELETE CASCADE,
    option_id BIGINT REFERENCES options(id) ON DELETE CASCADE,
    health INT NOT NULL DEFAULT 10,
    status VARCHAR(20) NOT NULL   -- STARTED | RESTARTED | STOPPED | FAILED | SUCCEEDED
);

-- --------------------
-- Indexes
-- --------------------
CREATE INDEX IF NOT EXISTS idx_sections_book_id ON sections(book_id);
CREATE INDEX IF NOT EXISTS idx_options_section_id ON options(section_id);
CREATE INDEX IF NOT EXISTS idx_games_book_id ON games(book_id);
CREATE INDEX IF NOT EXISTS idx_books_condition ON books(condition);
CREATE INDEX IF NOT EXISTS idx_games_status ON games(status);